# Generated by Django 4.2.4 on 2023-10-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_course_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
