# Generated by Django 4.2.4 on 2023-10-24 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Learning Material', max_length=122)),
                ('file', models.FileField(default='learning_materials/default.pdf', upload_to='learning_materials/')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
