# Generated by Django 4.2.4 on 2023-10-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_learningmaterial_delete_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='learners',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='learning_materials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.learningmaterial'),
        ),
    ]
