# Generated by Django 4.2.4 on 2023-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_quizscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='school.comment'),
        ),
    ]
