# Generated by Django 4.2.4 on 2023-12-02 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0028_alter_video_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_picture', models.ImageField(default='images/default.png', upload_to='images/')),
                ('name', models.CharField(default='', max_length=122)),
                ('info', models.CharField(default='', max_length=122)),
                ('github', models.CharField(default='', max_length=122)),
                ('linkedin', models.CharField(default='', max_length=122)),
                ('other', models.CharField(default='', max_length=122)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
