# Generated by Django 4.2.4 on 2023-12-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_learnerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='display_picture',
            field=models.ImageField(default='profiles/profile.png', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, to='school.comment'),
        ),
    ]
