# Generated by Django 4.2.4 on 2023-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_alter_learnerprofile_display_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='display_picture',
            field=models.ImageField(default='profiles/profile.jpg', upload_to='profiles/'),
        ),
    ]
