# Generated by Django 4.2.4 on 2023-12-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_learnerprofile_display_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Queztion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('choizes', models.ManyToManyField(blank=True, default=None, to='school.choize')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Quiz', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('queztion', models.ManyToManyField(blank=True, default=None, to='school.queztion')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='name',
            field=models.CharField(default='No name provided', max_length=122),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AlterField(
            model_name='course',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.quizz'),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.quizz'),
        ),
        migrations.AlterField(
            model_name='video',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.quizz'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
