# Generated by Django 4.2.4 on 2023-12-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_choize_queztion_quizz_remove_question_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queztion',
            name='choizes',
        ),
        migrations.AddField(
            model_name='choize',
            name='Queztion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.queztion'),
        ),
    ]
