# Generated by Django 4.2.4 on 2023-12-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cuid',
        ),
    ]
