# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/programming-for-data-science-site',
                'doc_host': 'https://courses.dataidea.org',
                'git_url': 'https://github.com/dataidea/programming-for-data-science-site',
                'lib_path': 'programming_for_data_science_site'},
  'syms': { 'programming_for_data_science_site.core': { 'programming_for_data_science_site.core.foo': ( 'core.html#foo',
                                                                                                        'programming_for_data_science_site/core.py')}}}
