project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  page-navigation: true
  reader-mode: true
  navbar:
    background: primary
    search: true
    logo: assets/dataidea-logo.png
    right:
      - text: Home
        href: 'https://www.dataidea.org/'
      - text: About
        href: 'https://docs.dataidea.org/about'
      - text: Resources
        menu:
         - text: Materials
           url: 'https://api.dataidea.org/school/download-course-material/2'
         - text: Blog
           url: 'https://blog.dataidea.org'
         - text: Forum
           url: 'https://chat.whatsapp.com/GuCZRyJICgO3Y7MPvDQKhi'
      - text: Contact
        href: 'https://docs.dataidea.org/contact'
  sidebar:
    style: "floating"
    favicon: assets/dataidea-logo.png
    twitter-card:
    creator: "@juma_shafara"
    site: "@datas_idea"

metadata-files: [nbdev.yml, sidebar.yml]
