# Generated by Django 4.2.4 on 2023-12-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='FrequentlyAskedQuestion',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='price',
            name='service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
