# Generated by Django 4.2.4 on 2023-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_devotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Secret Label', max_length=255)),
                ('value', models.CharField(default='Secret Value', max_length=255)),
            ],
        ),
    ]
