# Generated by Django 4.2.4 on 2023-10-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_secret"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Devotion",
        ),
    ]
